### ISSUE TITLE
schedule.rb:37-42: New scheduling types like 'at', 'once'...

### ISSUE THREAD

**Issue by 0pdd** [dgroup/lazylead#130]
The puzzle `DEV-e234446b` from #DEV has to be resolved: 

https://github.com/dgroup/lazylead/blob/37c35874b93f82ac20f4c96ec8add5bd15f9c593/lib/lazylead/schedule.rb#L37-L42

The puzzle was created by Yurii Dubinka on 06-Jun-20. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dgroup** [comment]
That's a key feature for app. skeleton during unit testing

**Comment by 0pdd** [comment]
The puzzle `DEV-e234446b` has disappeared from the source code, that's why I closed this issue.
