### ISSUE TITLE
touch_test.rb:34-37: Find stable svn repo which can be...

### ISSUE THREAD

**Issue by 0pdd** [dgroup/lazylead#189]
The puzzle `DEV-5661d0b8` from #DEV has to be resolved: 

https://github.com/dgroup/lazylead/blob/a707fd5a8d0abd0eb8d33c0cb99142eb0d59601f/test/lazylead/task/touch_test.rb#L34-L37

The puzzle was created by Yurii Dubinka on 05-Aug-20. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `DEV-5661d0b8` has disappeared from the source code, that's why I closed this issue.

**Comment by dgroup** [comment]
@rultor release tag=`0.4.3`
