### ISSUE TITLE
Rule AlertIf 

### ISSUE THREAD

**Issue by dgroup** [dgroup/lazylead#319]
The rule is required when we need to send a notification when special conditions/events happen with an issue.

**Comment by 0pdd** [comment]
@dgroup the puzzle [#327](https://github.com/dgroup/lazylead/issues/327) is still not solved.

**Comment by 0pdd** [comment]
@dgroup 2 puzzles [#332](https://github.com/dgroup/lazylead/issues/332), [#333](https://github.com/dgroup/lazylead/issues/333) are still not solved; solved: [#327](https://github.com/dgroup/lazylead/issues/327).

**Comment by 0pdd** [comment]
@dgroup all 3 puzzles are solved here: [#327](https://github.com/dgroup/lazylead/issues/327), [#332](https://github.com/dgroup/lazylead/issues/332), [#333](https://github.com/dgroup/lazylead/issues/333).
