### ISSUE TITLE
Add memes for accuracy rule

### ISSUE THREAD

**Issue by dgroup** [dgroup/lazylead#339]
Memes

> https://developerslife.ru/17054
> https://developerslife.ru/58

**Comment by VikNik599** [comment]
0:
https://developerslife.ru/327
https://developerslife.ru/16
80+:
https://developerslife.ru/139

**Comment by 0pdd** [comment]
@dgroup 2 puzzles [#468](https://github.com/dgroup/lazylead/issues/468), [#469](https://github.com/dgroup/lazylead/issues/469) are still not solved.
