### ISSUE TITLE
Speedup minitests tests and use multipe cores instead of one

### ISSUE THREAD

**Issue by dgroup** [dgroup/lazylead#445]
- https://stackoverflow.com/questions/26297653/why-arent-my-minitest-tests-being-run-in-parallel
- https://chriskottom.com/blog/2014/10/exploring-minitest-concurrency/
- https://github.com/sporkrb/spork
- https://stackoverflow.com/questions/6656935/how-to-run-multiple-rails-unit-tests-at-once
- https://stackoverflow.com/questions/19839689/run-rails-rake-test-in-parallel-on-multiple-cores-speeding-it-up-using-mini
- https://github.com/grosser/parallel_tests

**Comment by dgroup** [comment]
@VikNik599 попробовал поиграться MT_CPU, сильного прироста не увидел, было 67s, после MT_CPU=8 получил 58s.
Основной ботл нек это тесты которые завязаны на внешнюю джиру.
```
Index: Rakefile
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- Rakefile	(revision 67d1ea0012c0f125d7e9de55c74f4c5851fccf33)
+++ Rakefile	(date 1629580555696)
@@ -28,6 +28,7 @@
 require "rdoc"
 require "colorize"
 require "rake/clean"
+require "etc"
 
 # @todo #/DEV Investigate the possibility of using migrations from active_record
 #  - Rake tasks https://gist.github.com/schickling/6762581
@@ -50,6 +51,7 @@
 require "rake/testtask"
 desc "Run all unit tests"
 Rake::TestTask.new(:test) do |t|
+  ENV["MT_CPU"] = Etc.nprocessors.to_s
   t.libs << "test"
   t.libs << "lib"
   t.test_files = FileList["test/**/*_test.rb"]
```

**Comment by VikNik599** [comment]
А ты добавил parallelize_me! в Lazylead::Test?
`  class Test < ActiveSupport::TestCase
    include Minitest::Hooks

    parallelize_me!
    make_my_diffs_pretty!`

**Comment by VikNik599** [comment]
Короче, добавил немного логирования, увеличение времени выполнения тестов в определенный момент увеличивается именно из-за установления соединения с БД - оно после определенного момента занимает 10s.

```
Lazylead::PredefinedCcTest
Connection established in 0 s
  test_detect_plain_cc                                            PASS (0.01s)
  test_cc_by_component_is_found                                   SKIP (0.00s)
  test_cc_by_key_is_found                                         PASS (0.00s)
  test_all_predefined_cc_are_valid_emails                         PASS (0.00s)
Connection established in 0 s
  test_detect_complex_cc_by_predefined_component                  PASS (0.01s)
  test_predefined_cc_has_valid_emails                             PASS (0.00s)
  test_bulk_search_in_few_iterations                              PASS (4.90s)
  test_last_change_to_Done                                        PASS (1.31s)
  test_detect_affected_build                                      PASS (1.40s)
Connection established in 10 s
  test_issue_#154_undefined_method_to_hash_for_nil_object         PASS (10.02s)
Connection established in 10 s
  test_task_properties_are_parsed_despite_on_wrong_config         PASS (10.01s)
Connection established in 10 s
  test_convert_column_to_json                                     PASS (10.01s)
Connection established in 10 s
  test_construct_accuracy_from_orm                                PASS (10.01s)
```

Пытаюсь решить.

**Comment by VikNik599** [comment]
@dgroup, запилил кое-какое решение, можешь посмотреть [https://github.com/VikNik599/lazylead/commit/ca0eb0af858a80cf0af4fd1de663bf62c25fd4ed](тут). Но оно все еще ведет себя не очень стабильно. Есть две проблемы:

1. Иногда тест падает, потому что не может выделить connection pool.
`ActiveRecord::ConnectionNotEstablished: No connection pool for 'ActiveRecord::Base' found.`
2. Все еще есть проблема с зависанием теста в некоторых случаях(в основном один тест в конце) из за того, что установка соединения занимает 10 секунд.

Пытаюсь найти решение, но если есть идеи буду рад услышать.
